server:
  port: 8762
spring:
  application:
    name: zuul-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
zuul:
  #Service will be mapped under the /api URI
  routes:
    users:
      serviceId: users
  host:
    socket-timeout-millis: 30000