server:
  port: 8762
spring:
  application:
    name: zuul-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
zuul:
  #Service will be mapped under the /api URI
  routes:
    realtors:
      serviceId: realtors
    real-estate:
      serviceId: real-estate
    tasks:
      serviceId: tasks
  host:
    socket-timeout-millis: 30000
swagger:
  enabled: true