server:
  port: 8762
spring:
  application:
    name: zuul-server
eureka:
  client:
    serviceUrl:
#      defaultZone: http://eureka-app-server:8761/eureka/
       defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
zuul:
  #Service will be mapped under the /api URI
  routes:
    realtors:
      serviceId: realtors
    real-estate:
      serviceId: real-estate
    tasks:
      serviceId: tasks
    clients:
      serviceId: clients
    properties:
      serviceId: properties
  host:
    socket-timeout-millis: 30000
swagger:
  enabled: true