spring:
  data:
    mongodb:
      database: tasks
      uri: mongodb://localhost:27017
#     uri: mongodb://mongo:27017
#     uri: mongodb+srv://admin:admin@cluster0-yuvo1.mongodb.net/tasks?retryWrites=true&w=majority
  application:
    name: tasks
server:
#  servlet:
#   context-path: /users
  port: 8082
eureka:
  client:
    serviceUrl:
      #  defaultZone: http://eureka-server-app:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
swagger:
  enabled: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic