spring:
  data:
    mongodb:
      database: users
      uri: mongodb://localhost:27017
  application:
    name: users
server:
#  servlet:
#   context-path: /users
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
swagger:
  enabled: true
  
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: basic