spring:
  data:
    mongodb:
      database: real-estate
      uri: mongodb://localhost:27017
      #  uri: mongodb+srv://admin:admin@cluster0-yuvo1.mongodb.net/real-estate?retryWrites=true&w=majority
  application:
    name: real-estate
server:
#  servlet:
#   context-path: /users
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-app:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
swagger:
  enabled: true
