spring:
  data:
    mongodb:
      database: clients
      # uri: mongodb://localhost:27017
      uri: mongodb+srv://admin:admin@cluster0-yuvo1.mongodb.net/clients?retryWrites=true&w=majority
  application:
    name: clients
server:
  #  servlet:
  #   context-path: /realtors
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
swagger:
  enabled: true