spring:
  data:
    mongodb:
      database: realtors
      # uri: mongodb://localhost:27017
      uri: mongodb+srv://admin:admin@cluster0-yuvo1.mongodb.net/realtors?retryWrites=true&w=majority
  application:
    name: realtor
server:
  #  servlet:
  #   context-path: /realtors
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
swagger:
  enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic