spring:
  data:
    mongodb:
      database: properties
      #  uri: mongodb://localhost:27017
      uri: mongodb+srv://admin:admin@cluster0-yuvo1.mongodb.net/properties?retryWrites=true&w=majority
  application:
    name: properties
server:
  #  servlet:
  #   context-path: /users
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
swagger:
  enabled: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

