spring:
  data:
    mongodb:
      database: buildings
      uri: mongodb://localhost:27017
  application:
    name: buildings
server:
  #  servlet:
  #   context-path: /realtors
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
swagger:
  enabled: true
